import type { Thesis, Conviction, Signal, MarketEvent } from "@/types";

export const mockTheses: Thesis[] = [
  {
    id: "1",
    title: "NVDA AI Infrastructure Dominance",
    description:
      "NVIDIA will maintain GPU market leadership through 2027 as AI training demand outpaces competitor supply. CUDA ecosystem creates durable switching costs.",
    confidence: 85,
    status: "conviction",
    tags: ["semiconductor", "AI", "infrastructure"],
    createdAt: "2026-03-15",
    updatedAt: "2026-05-18",
    assumptions: [
      {
        id: "a1",
        text: "AI training compute demand grows >40% YoY through 2027",
        status: "validated",
        impact: "high",
        category: "demand",
      },
      {
        id: "a2",
        text: "CUDA ecosystem switching costs exceed $10B for hyperscalers",
        status: "validated",
        impact: "high",
        category: "competitive",
      },
      {
        id: "a3",
        text: "AMD MI400 series does not achieve >30% market share by Q4 2026",
        status: "holding",
        impact: "medium",
        category: "competitive",
      },
      {
        id: "a4",
        text: "Custom silicon (TPU, Trainium) remains niche to single cloud providers",
        status: "validated",
        impact: "medium",
        category: "technical",
      },
    ],
    risks: [
      { id: "r1", text: "China export restrictions tighten further", severity: "high", status: "active", createdAt: "2026-03-15" },
    ],
  },
  {
    id: "2",
    title: "TSLA Robotaxi Optionality",
    description:
      "Tesla's autonomous driving data moat is undervalued. FSD fleet miles create a flywheel competitors cannot replicate. Robotaxi launch will rerate the stock.",
    confidence: 52,
    status: "reviewing",
    tags: ["EV", "autonomous", "AI"],
    createdAt: "2026-02-10",
    updatedAt: "2026-05-12",
    assumptions: [
      {
        id: "a1",
        text: "FSD achieves L4 certification in at least 3 US states by end of 2026",
        status: "holding",
        impact: "high",
        category: "regulatory",
      },
      {
        id: "a2",
        text: "Tesla fleet drives >5B miles with FSD active by Q3 2026",
        status: "validated",
        impact: "high",
        category: "technical",
      },
      {
        id: "a3",
        text: "Waymo expansion slows due to mapping cost constraints",
        status: "invalidated",
        impact: "medium",
        category: "competitive",
      },
      {
        id: "a4",
        text: "Regulatory framework does not favor incumbent automakers",
        status: "holding",
        impact: "medium",
        category: "regulatory",
      },
      {
        id: "a5",
        text: "Insurance liability model for robotaxi becomes commercially viable",
        status: "holding",
        impact: "low",
        category: "macro",
      },
    ],
    risks: [
      { id: "r2", text: "Waymo partnership with Hyundai accelerates competition", severity: "high", status: "materialized", createdAt: "2026-03-20" },
    ],
  },
  {
    id: "3",
    title: "ASML Monopoly on EUV Lithography",
    description:
      "ASML is the sole supplier of EUV machines critical for advanced chip manufacturing. Supply constraints and rising demand guarantee pricing power through 2028.",
    confidence: 78,
    status: "active",
    tags: ["semiconductor", "equipment", "monopoly"],
    createdAt: "2026-01-20",
    updatedAt: "2026-05-05",
    assumptions: [
      {
        id: "a1",
        text: "No viable EUV alternative emerges from China or Japan by 2027",
        status: "validated",
        impact: "high",
        category: "competitive",
      },
      {
        id: "a2",
        text: "TSMC, Samsung, Intel all increase EUV capex in next 18 months",
        status: "validated",
        impact: "high",
        category: "demand",
      },
      {
        id: "a3",
        text: "High-NA EUV adoption follows projected timeline",
        status: "holding",
        impact: "medium",
        category: "technical",
      },
    ],
    risks: [],
  },
  {
    id: "4",
    title: "PLTR Government AI Contract Expansion",
    description:
      "Palantir's AIP platform positions it as the default AI layer for US government. Contract pipeline suggests 40%+ revenue growth in federal segment.",
    confidence: 64,
    status: "active",
    tags: ["government", "AI", "SaaS"],
    createdAt: "2026-04-01",
    updatedAt: "2026-05-15",
    assumptions: [
      {
        id: "a1",
        text: "US federal AI spending exceeds $15B in FY2027",
        status: "holding",
        impact: "high",
        category: "demand",
      },
      {
        id: "a2",
        text: "AIP wins at least 3 new $100M+ contracts in 2026",
        status: "holding",
        impact: "high",
        category: "demand",
      },
      {
        id: "a3",
        text: "Competitor offerings (Anduril, Scale AI) do not erode Palantir's moat",
        status: "holding",
        impact: "medium",
        category: "competitive",
      },
      {
        id: "a4",
        text: "Commercial segment growth does not cannibalize government focus",
        status: "validated",
        impact: "low",
        category: "management",
      },
    ],
    risks: [],
  },
  {
    id: "5",
    title: "COIN Crypto Cycle Play",
    description:
      "Coinbase benefits from regulatory clarity and ETF inflows. Position as regulated on-ramp creates durable advantage as institutional adoption accelerates.",
    confidence: 38,
    status: "abandoned",
    tags: ["crypto", "fintech", "regulation"],
    createdAt: "2025-11-05",
    updatedAt: "2026-04-20",
    assumptions: [
      {
        id: "a1",
        text: "Bitcoin ETF AUM exceeds $150B by Q2 2026",
        status: "invalidated",
        impact: "high",
        category: "demand",
      },
      {
        id: "a2",
        text: "SEC does not impose restrictive DeFi regulations",
        status: "validated",
        impact: "medium",
        category: "regulatory",
      },
      {
        id: "a3",
        text: "Coinbase L2 (Base) captures >20% of L2 TVL",
        status: "invalidated",
        impact: "medium",
        category: "technical",
      },
    ],
    risks: [],
  },
];

export const mockConvictions: Conviction[] = [
  // NVDA conviction history
  { id: "c1", thesisId: "1", value: 65, reasoning: "Initial thesis based on AI demand trajectory", recordedAt: "2026-03-15" },
  { id: "c2", thesisId: "1", value: 72, reasoning: "Q1 earnings confirmed datacenter growth", recordedAt: "2026-04-02" },
  { id: "c3", thesisId: "1", value: 80, reasoning: "CUDA adoption data stronger than expected", recordedAt: "2026-04-20" },
  { id: "c4", thesisId: "1", value: 85, reasoning: "Competitor delays confirmed, supply constraints holding", recordedAt: "2026-05-18" },
  // TSLA conviction history
  { id: "c5", thesisId: "2", value: 70, reasoning: "FSD data moat thesis intact", recordedAt: "2026-02-10" },
  { id: "c6", thesisId: "2", value: 62, reasoning: "Waymo expansion faster than expected, assumption challenged", recordedAt: "2026-03-15" },
  { id: "c7", thesisId: "2", value: 55, reasoning: "Regulatory uncertainty increasing", recordedAt: "2026-04-10" },
  { id: "c8", thesisId: "2", value: 52, reasoning: "No L4 certification progress yet", recordedAt: "2026-05-12" },
  // ASML conviction history
  { id: "c9", thesisId: "3", value: 70, reasoning: "EUV monopoly thesis", recordedAt: "2026-01-20" },
  { id: "c10", thesisId: "3", value: 75, reasoning: "Capex guidance from TSMC confirmed", recordedAt: "2026-03-01" },
  { id: "c11", thesisId: "3", value: 78, reasoning: "No competitor alternatives emerging", recordedAt: "2026-05-05" },
];

export const mockSignals: Signal[] = [
  { id: "s1", thesisId: "1", assumptionId: "a1", source: "earnings", content: "Microsoft Azure AI revenue grew 48% YoY in Q1 2026", direction: "supportive", strength: "strong", timestamp: "2026-04-25" },
  { id: "s2", thesisId: "1", assumptionId: "a2", source: "news", content: "Google announces $10B+ investment in custom TPUs for 2027", direction: "contradicting", strength: "moderate", timestamp: "2026-05-10" },
  { id: "s3", thesisId: "2", assumptionId: "a3", source: "news", content: "Waymo expands to 5 new cities, partnership with Hyundai confirmed", direction: "contradicting", strength: "strong", timestamp: "2026-03-20" },
  { id: "s4", thesisId: "3", assumptionId: "a1", source: "news", content: "Canon announces EUV prototype, but 3+ years from production", direction: "supportive", strength: "moderate", timestamp: "2026-04-15" },
  { id: "s5", thesisId: "4", assumptionId: "a2", source: "news", content: "Palantir wins $480M Army contract extension", direction: "supportive", strength: "strong", timestamp: "2026-05-01" },
];

export const mockEvents: MarketEvent[] = [
  {
    id: "e1",
    title: "Microsoft Azure AI Revenue Grows 48% YoY",
    summary: "Microsoft reported Q1 2026 earnings with Azure AI revenue growing 48% year-over-year, exceeding analyst expectations. Enterprise AI adoption accelerating faster than projected.",
    source: "Microsoft Q1 2026 Earnings",
    category: "earnings",
    sentiment: "positive",
    entities: ["Microsoft", "Azure", "AI"],
    relatedThesisIds: ["1"],
    relatedAssumptionIds: ["a1"],
    impactScore: 75,
    reasoning: "Directly validates the AI infrastructure demand thesis. Enterprise AI spending growth exceeding expectations supports the assumption that compute demand grows >40% YoY.",
    createdAt: "2026-04-25",
  },
  {
    id: "e2",
    title: "Google Invests $10B+ in Custom TPUs",
    summary: "Google announced over $10 billion investment in custom TPU infrastructure for 2027, signaling a major push into proprietary AI silicon that could challenge NVIDIA's GPU dominance.",
    source: "Google Cloud Next 2026",
    category: "news",
    sentiment: "mixed",
    entities: ["Google", "TPU", "NVIDIA"],
    relatedThesisIds: ["1"],
    relatedAssumptionIds: ["a2", "a4"],
    impactScore: -30,
    reasoning: "Challenges the CUDA switching cost assumption. If Google's custom silicon proves viable, it could reduce hyperscaler dependency on NVIDIA GPUs. However, TPU remains niche to Google.",
    createdAt: "2026-05-10",
  },
  {
    id: "e3",
    title: "Waymo-Hyundai Partnership Expands Autonomous Fleet",
    summary: "Waymo and Hyundai confirmed a partnership to deploy autonomous vehicles across 5 new cities, significantly expanding the competitive landscape for autonomous driving technology.",
    source: "Waymo Press Release",
    category: "company",
    sentiment: "negative",
    entities: ["Waymo", "Hyundai", "Tesla"],
    relatedThesisIds: ["2"],
    relatedAssumptionIds: ["a3"],
    impactScore: -60,
    reasoning: "Directly invalidates the assumption that Waymo expansion would slow due to mapping costs. The Hyundai partnership provides manufacturing scale that reduces per-unit costs significantly.",
    createdAt: "2026-03-20",
  },
  {
    id: "e4",
    title: "Canon Announces EUV Lithography Prototype",
    summary: "Canon unveiled a prototype EUV lithography machine, but industry analysts estimate it is 3+ years from production-ready status and significantly trails ASML's current capabilities.",
    source: "Nikkei Asia",
    category: "news",
    sentiment: "positive",
    entities: ["Canon", "ASML", "EUV"],
    relatedThesisIds: ["3"],
    relatedAssumptionIds: ["a1"],
    impactScore: 40,
    reasoning: "Reinforces the ASML monopoly thesis. While Canon is attempting to enter the EUV market, the 3+ year timeline and capability gap confirm that no viable alternative exists in the near term.",
    createdAt: "2026-04-15",
  },
  {
    id: "e5",
    title: "Palantir Wins $480M Army Contract Extension",
    summary: "Palantir Technologies secured a $480 million contract extension with the US Army for its AI-powered intelligence platform, reinforcing its position as a key government AI provider.",
    source: "Palantir 8-K Filing",
    category: "company",
    sentiment: "positive",
    entities: ["Palantir", "US Army", "AIP"],
    relatedThesisIds: ["4"],
    relatedAssumptionIds: ["a2"],
    impactScore: 65,
    reasoning: "Validates the thesis that Palantir's AIP platform is becoming the default AI layer for US government. A $480M extension demonstrates strong contract renewal rates and deepening government dependency.",
    createdAt: "2026-05-01",
  },
  {
    id: "e6",
    title: "Fed Signals Extended Higher-for-Longer Rate Stance",
    summary: "Federal Reserve officials indicated that interest rates will remain elevated longer than markets expected, citing persistent inflation in services and strong labor market data.",
    source: "FOMC Meeting Minutes",
    category: "macro",
    sentiment: "negative",
    entities: ["Federal Reserve", "Interest Rates"],
    relatedThesisIds: ["1", "2", "4"],
    relatedAssumptionIds: [],
    impactScore: -45,
    reasoning: "Higher rates reduce the present value of future growth cash flows, pressuring valuations across growth-oriented theses. Particularly impacts TSLA (rate-sensitive valuation) and PLTR (government spending may tighten).",
    createdAt: "2026-05-15",
  },
];
